export const GET_CONVERSATIONS_REQUEST = 'GET_CONVERSATIONS_REQUEST';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILURE = 'GET_CONVERSATIONS_FAILURE';

export const GET_CONVERSATION_DETAIL_REQUEST = 'GET_CONVERSATION_DETAIL_REQUEST';
export const GET_CONVERSATION_DETAIL_SUCCESS = 'GET_CONVERSATION_DETAIL_SUCCESS';
export const GET_CONVERSATION_DETAIL_FAILURE = 'GET_CONVERSATION_DETAIL_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const getConversationsRequest = () => ({
  type: GET_CONVERSATIONS_REQUEST,
});

export const getConversationDetailRequest = payload => ({
  type: GET_CONVERSATION_DETAIL_REQUEST,
  payload
});

export const sendMessageRequest = payload => ({
  type: SEND_MESSAGE_REQUEST,
  payload
});

